language: rust
sudo: false
rust:
  - stable
  - nightly
  - beta
cache: cargo

notifications:
  email:
    recipients: paho@paholg.com

before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
  - export TRAVIS_CARGO_NIGHTLY_FEATURE=""
  - test -x $HOME/.cargo/bin/rustfmt || cargo install rustfmt # Only install rustfmt if it's not there

script:
  - |
    PATH=$PATH:~/.cargo/bin cargo fmt -- --write-mode=diff &&
    travis-cargo build &&
    travis-cargo test &&
    # Note: The "no_std" flag is deprecated and this test remains to make sure we don't break compatibility.
    travis-cargo --only stable test -- --features "no_std" &&
    travis-cargo --only nightly test -- --features "clippy" &&
    travis-cargo --only stable doc

after_success:
  - travis-cargo --only stable doc-upload
  - test $TRAVIS_PULL_REQUEST == "false" &&
    test $TRAVIS_BRANCH == "master" &&
    cargo publish --token ${CRATESIO_TOKEN}

env:
  global:
    # GitHub SSH stuff
    - ENCRYPTION_LABEL: "1a1e1556d2a8"
    - COMMIT_AUTHOR_EMAIL: "paho@paholg.com"
    # CRATESIO_TOKEN
    - secure: "cchJKaN5hM2ceBpLqDokhUWFUyFubTlrUxj8d/5JjDXOxVvpZQWQuPxihnSyz0U+GSY4HwUh8C9+jRe2i8UBmhS6pPMG4Bl0Xo2T1HU9ilWb43vSqsbg77UgQ2SELNd+7g1xSI/UTsaFH0YlTOw7DsF6plruVduyOy8C44Ox1nAo4hIgN1ThRs9nhKTWydREr2zRQ/7n4c99RnPQz54ITnrHx/Ks2bvy3zgTOP7CeiQQJKh521U5tuH23r48eljje7776UA4Jbs2j1LsnMaBsraadIzNMopEwaSE1oNLOobfWG9YzvyTZ2i4yElDX4A7tscwo631Ig5AUH2+QbvN2k0q2EKETQJ9Mov5OSmK3aeMSW1GA3hQ44Uvz0F7SZru8D84sKgfSXNbfck1hTVfBPPOpmUIKDb+rSthulYq2SW2XG9cpVXrJmhYD2WTNKEuSmw7imVbTCPS03dbbMoLchpmOBkcgLtcMNDyC94xdZYSkyz9+RCG0bEfwIu9oG7o6gv+8a42pgVSP8mfOOq0+MELHntIqumlmTO0jGGH10Prs4Pgs8eVn6S84w+oz8yrbYroVaqrI2TZl73KnOmvAlnYZdCSIBGV5XsTukzochfwgaTKWI2h2iK1yt6k5I5ZgOoVlTUPB4ElwhIDfgYhc7fltHd53EO81GHGDPSI49M="
