[package]
name = "typenum"
version = "0.0.2"
authors = ["Paho Lurie-Gregg <paho@paholg.com>"]
description = "Type-level numbers."
homepage = "http://paholg.com/typenum"
documentation = "http://paholg.com/doc/typenum"
repository = "https://github.com/paholg/typenum"
readme = "README.md"
license = "MIT/Apache-2.0"

[lib]
name = "typenum"
plugin = true
